name: Docker Hub + Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    
    env:
      NOME_IMAGEM: testesitecontagem
      NOME_COMPLETO_IMAGEM: ${{ secrets.DOCKER_USERNAME }}/$NOME_IMAGEM
      NOME_WEBAPP: groffesitecontagem0

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login no Docker Hub
      uses: docker/login-action@v1.6.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push no Docker Hub
      run: |
        cd ./SiteContagem
        docker build . --file Dockerfile --tag ${{ env.NOME_COMPLETO_IMAGEM }}:latest
        docker tag ${{ env.NOME_COMPLETO_IMAGEM }}:latest ${{ env.NOME_COMPLETO_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.NOME_COMPLETO_IMAGEM }}
        
    - name: Azure Login - Conectando com Credenciais no Azure
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure WebApp - Deployment da Aplicacao
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.NOME_WEBAPP }}
        images: 'renatogroffe/testesitecontagem:${{ github.run_number }}'